#ifndef CONFIG_H
#define CONFIG_H

#cmakedefine VDF_REAL_DTYPE @VDF_REAL_DTYPE@
#cmakedefine OCTREE_TUCKER_CORE_RANK @OCTREE_TUCKER_CORE_RANK@
#cmakedefine MAX_ROOT_DIMS
#cmakedefine OCTREE_VIEW_INDEX_TYPE
#cmakedefine OCTREE_RANGE_CHECK

#endif // CONFIG_H
